name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Print something
        run: echo Hello Ranjan
      - name: Print age
        run: echo 22
      
